# Site settings
title: siteco.xyz
email: sitecoxyz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  SitecoXYZ portfolio site.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  sitecoxyz

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/


